apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-k8s-deployment
  labels:
    app: hello-k8s
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 30
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
        version: "1.0"
        tier: frontend
    spec:
      containers:
      - name: hello-k8s
        image: zodoz/kubernetes-basics:01-hello-k8s
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80